---
- hosts: all
  become: true
  become_user: joan.iznardo
  remote_user: joan.iznardo
  #  become_user: root
  #  remote_user: vagrant
  gather_facts: false
  tasks:
   - name: kvm_install
     hosts: all
     become: yes
     gather_facts: True
     apt: name={{ item }} state=installed
     with_items:
       - qemu
       - qemu-kvm
       - libvirt-bin
       - bridge-utils
       - virt-manager
